//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebControlArchivo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArchivoEntities : DbContext
    {
        public ArchivoEntities()
            : base("name=ArchivoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<Detalle_Prestamos> Detalle_Prestamos { get; set; }
        public virtual DbSet<Documento> Documentos { get; set; }
        public virtual DbSet<Fraccionamiento> Fraccionamientos { get; set; }
        public virtual DbSet<Localidade> Localidades { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<Prestamo> Prestamos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<View_ListadodeFraccionamientos> View_ListadodeFraccionamientos { get; set; }
        public virtual DbSet<View_ListadoPersonal> View_ListadoPersonal { get; set; }
        public virtual DbSet<View_Localidades> View_Localidades { get; set; }
    }
}
