//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebControlArchivo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Prestamos
    {
        public int Id_Detalle_Prestamo { get; set; }
        public int Id_Prestamo { get; set; }
        public int Id_Documento { get; set; }
    }
}
