//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebControlArchivo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int Id_Personal { get; set; }
        public int Id_Departamento { get; set; }
        public string Nombre { get; set; }
        public string BarCode { get; set; }
        public string Permisos { get; set; }
    }
}
