//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebControlArchivo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        public int Id_Prestamo { get; set; }
        public int Id_Solicitante { get; set; }
        public int Id_Autorizo { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
    }
}
