//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMaster.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DM_CT_PESLPEntities : DbContext
    {
        public DM_CT_PESLPEntities()
            : base("name=DM_CT_PESLPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accione> Acciones { get; set; }
        public virtual DbSet<Depto> Deptos { get; set; }
        public virtual DbSet<Documento> Documentos { get; set; }
        public virtual DbSet<DT> DTs { get; set; }
        public virtual DbSet<ENT> ENTs { get; set; }
        public virtual DbSet<Fraccionamiento> Fraccionamientos { get; set; }
        public virtual DbSet<Medida> Medidas { get; set; }
        public virtual DbSet<Orientacione> Orientaciones { get; set; }
        public virtual DbSet<Puesto> Puestos { get; set; }
        public virtual DbSet<SC> SCs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tramite> Tramites { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<ArchivosFracc> ArchivosFraccs { get; set; }
        public virtual DbSet<ASs> ASses { get; set; }
        public virtual DbSet<BitEtapa> BitEtapas { get; set; }
        public virtual DbSet<DET> DETs { get; set; }
        public virtual DbSet<DSs> DSses { get; set; }
        public virtual DbSet<Etapa> Etapas { get; set; }
        public virtual DbSet<ET> ETs { get; set; }
        public virtual DbSet<FN> FNs { get; set; }
        public virtual DbSet<NotariaContacto> NotariaContactos { get; set; }
        public virtual DbSet<NotariaEtapa> NotariaEtapas { get; set; }
        public virtual DbSet<NotariaPuesto> NotariaPuestos { get; set; }
        public virtual DbSet<Notaria> Notarias { get; set; }
        public virtual DbSet<Programa> Programas { get; set; }
        public virtual DbSet<Solicitude> Solicitudes { get; set; }
        public virtual DbSet<SolicitudNE> SolicitudNEs { get; set; }
        public virtual DbSet<TF> TFs { get; set; }
        public virtual DbSet<UZ> UZs { get; set; }
        public virtual DbSet<Zona> Zonas { get; set; }
        public virtual DbSet<vwAgenda> vwAgendas { get; set; }
        public virtual DbSet<vwAgendaEjecucion> vwAgendaEjecucions { get; set; }
        public virtual DbSet<vwAgendaValidacion> vwAgendaValidacions { get; set; }
        public virtual DbSet<vwBitEtapa> vwBitEtapas { get; set; }
        public virtual DbSet<vwDET> vwDETs { get; set; }
        public virtual DbSet<vwDSs> vwDSses { get; set; }
        public virtual DbSet<vwENT> vwENTs { get; set; }
        public virtual DbSet<vwEtapa> vwEtapas { get; set; }
        public virtual DbSet<vwET> vwETs { get; set; }
        public virtual DbSet<vwFN> vwFNs { get; set; }
        public virtual DbSet<vwFraccionamiento> vwFraccionamientos { get; set; }
        public virtual DbSet<vwMedida> vwMedidas { get; set; }
        public virtual DbSet<vwNotariaContacto> vwNotariaContactos { get; set; }
        public virtual DbSet<vwSolicitude> vwSolicitudes { get; set; }
        public virtual DbSet<vwTF> vwTFs { get; set; }
        public virtual DbSet<vwUsuario> vwUsuarios { get; set; }
    }
}
